/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Abstract.Buildings;
import IsABuilding.Coop;
import IsABuilding.Cowshed;
import IsABuilding.Silo;
import IsABuilding.Stable;
import SystemAndMain.BuildingSys;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class SetFarmFrame extends javax.swing.JFrame {

    StartFrame sf = new StartFrame();
    ManageBuildings mb = new ManageBuildings(this);
    ManageAnimals ma;
    SetPrices sp = new SetPrices(this);
    Buildings b;
    
    public SetFarmFrame(String name) {
        initComponents();
        
        setTitle("Info-FarmLand");
        setLocationRelativeTo(null);
        
        lblName.setText("Hello " + name + "!");
        lblBudget.setText("Budget: " + BuildingSys.budget + " $");        
        
        b = new Coop(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString())); 
        lblCost.setText("" + b.calculateCost());
        
        b.calculateCapacity();
        lblCapacity.setText("" + ((Coop) b).getCapacityForChicken() + " chickens");       
    }

    public void setLblBudget(String newBudget) {
        lblBudget.setText(newBudget);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPassAYear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        cmbType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMaterial = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnManageAnimals = new javax.swing.JButton();
        btnSetPrices = new javax.swing.JButton();
        cmbNumOfFloors = new javax.swing.JComboBox<>();
        btnDisplay = new javax.swing.JButton();
        btnManageBuildigs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPassAYear.setText("Pass A Year");
        btnPassAYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassAYearActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassAYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 110, -1));

        jPanel2.setBackground(new java.awt.Color(177, 255, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 20));
        jPanel2.add(lblBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, 20));

        btnRestart.setText("Restart!");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });
        jPanel2.add(btnRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 20));

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 10, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 310, 270));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coop", "Cowshed", "Silo", "Stable" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        jLabel1.setText("Building Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setText("Material:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        cmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wooden", "Stone", "Concrete" }));
        cmbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        jLabel3.setText("Number of Floors:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Building"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cost:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setText("Capacity:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel4.add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, 20));
        jPanel4.add(lblCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 100));

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Adding Building");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btnManageAnimals.setText("Manage Animals");
        btnManageAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAnimalsActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageAnimals, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btnSetPrices.setText("Set Prices");
        btnSetPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetPricesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSetPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 130, -1));

        cmbNumOfFloors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cmbNumOfFloors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNumOfFloorsActionPerformed(evt);
            }
        });
        jPanel1.add(cmbNumOfFloors, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 130, -1));

        btnManageBuildigs.setText("Manage Buildings");
        btnManageBuildigs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBuildigsActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageBuildigs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        sf.setVisible(true);
        BuildingSys.turnBackToDefault();
        dispose();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        String type = cmbType.getSelectedItem().toString();
        
        switch(type){
            case "Coop":
                b = new Coop(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Coop) b).getCapacityForChicken() + " chickens");
                break;
            case "Cowshed":
                b = new Cowshed(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Cowshed) b).getCapacityForCow() + " cows");
                break;
            case "Silo":
                b = new Silo(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Silo) b).getCapacityForFeed() + " kg");
                break;
            case "Stable":
                b = new Stable(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Stable) b).getCapacityForHorse() + " horses");
        }
        
        Buildings.decreaseIdS();
        lblCost.setText("" + b.calculateCost());                       
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void cmbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaterialActionPerformed
        String type = cmbType.getSelectedItem().toString();
        
        switch(type){
            case "Coop":
                b = new Coop(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Coop) b).getCapacityForChicken() + " chickens");
                break;
            case "Cowshed":
                b = new Cowshed(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Cowshed) b).getCapacityForCow() + " cows");
                break;
            case "Silo":
                b = new Silo(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Silo) b).getCapacityForFeed() + " kg");
                break;
            case "Stable":
                b = new Stable(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Stable) b).getCapacityForHorse() + " horses");
        }
        
        Buildings.decreaseIdS();
        lblCost.setText("" + b.calculateCost());
    }//GEN-LAST:event_cmbMaterialActionPerformed

    private void cmbNumOfFloorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNumOfFloorsActionPerformed
        String type = cmbType.getSelectedItem().toString();
        
        switch(type){
            case "Coop":
                b = new Coop(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Coop) b).getCapacityForChicken() + " chickens");
                break;
            case "Cowshed":
                b = new Cowshed(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Cowshed) b).getCapacityForCow() + " cows");
                break;
            case "Silo":
                b = new Silo(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Silo) b).getCapacityForFeed() + " kg");
                break;
            case "Stable":
                b = new Stable(cmbMaterial.getSelectedItem().toString(), 
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
                b.calculateCapacity();
                lblCapacity.setText("" + ((Stable) b).getCapacityForHorse() + " horses");
        }
        
        Buildings.decreaseIdS();
        lblCost.setText("" + b.calculateCost());
    }//GEN-LAST:event_cmbNumOfFloorsActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        boolean res = BuildingSys.addBuilding(cmbType.getSelectedItem().toString(), cmbMaterial.getSelectedItem().toString(),
                Integer.parseInt(cmbNumOfFloors.getSelectedItem().toString()));
        
        if (res)
            lblBudget.setText("Budget: " + BuildingSys.budget + " $");
        else
            JOptionPane.showMessageDialog(null,"The budget is not enough for purchase!","Error",1);
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        String res = BuildingSys.display();
        
        if(res == "")
            textArea.setText("There are no buildings.");
        else
            textArea.setText(res);
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnManageBuildigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBuildigsActionPerformed
        if(BuildingSys.list.size() == 0)
            JOptionPane.showMessageDialog(null,"There are no buildings to manage!","Error",1);
        else{
            mb.setVisible(true);
            fillComboBoxB();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnManageBuildigsActionPerformed

    private void btnManageAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAnimalsActionPerformed
        if(BuildingSys.list.size() == 0)
            JOptionPane.showMessageDialog(null,"There are no buildings to add animals!","Error",1);
        else{
            ma = new ManageAnimals(this);
            ma.setVisible(true);
            fillComboBoxA();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnManageAnimalsActionPerformed

    private void btnSetPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetPricesActionPerformed
        if(BuildingSys.areThereAnimals()){
            sp.setVisible(true);
            this.setVisible(false);
        }            
        else
            JOptionPane.showMessageDialog(null,"There are no animals to produce anything!","Error",1);
    }//GEN-LAST:event_btnSetPricesActionPerformed

    private void btnPassAYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassAYearActionPerformed
        if(BuildingSys.isHorsesDailyEnough() > 0)
            JOptionPane.showMessageDialog(null,"Not enough horses to pass the year!","Error",1);
        else if(!BuildingSys.areThereAnimals())
            JOptionPane.showMessageDialog(null,"There are no animals to pass the year!","Error",1);
        else if(!BuildingSys.isThereSilo())
            JOptionPane.showMessageDialog(null,"Build at least one silo!","Error",1);
        else if(!BuildingSys.isSiloCapacityEnough())
            JOptionPane.showMessageDialog(null,"Increase the number of silos!","Error",1);
        else{
            boolean res = BuildingSys.passAYear();
            if(res){
                textArea.setText("This year passed successfully!\nTotal years passed: " 
                        + BuildingSys.yearsPassed + "\n\n" + BuildingSys.display());
                lblBudget.setText("Budget: " + BuildingSys.budget + " $"); 
            }
            else
                JOptionPane.showMessageDialog(null,"Change your farm and try again, else your will bankrupt!","Error",1);
        }
    }//GEN-LAST:event_btnPassAYearActionPerformed

    public void fillComboBoxB(){
        mb.getCmbBuildings().setModel(new DefaultComboBoxModel(BuildingSys.getBuildingNames()));
    }
    
    public void fillComboBoxA(){
        ma.getCmbBuildings().setModel(new DefaultComboBoxModel(BuildingSys.getBuildingNames()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnManageAnimals;
    private javax.swing.JButton btnManageBuildigs;
    private javax.swing.JButton btnPassAYear;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnSetPrices;
    private javax.swing.JComboBox<String> cmbMaterial;
    private javax.swing.JComboBox<String> cmbNumOfFloors;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
