/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.BuildingSys;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class StartFrame extends javax.swing.JFrame {

    SetFarmFrame sff;
    public String name;
    
    public StartFrame() {
        initComponents();
        
        setTitle("Info-FarmLand");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfBudget = new javax.swing.JTextField();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Enter Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        jLabel3.setText("Enter Budget:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Plan your farm with us!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon.jpg"))); // NOI18N
        jLabel1.setText("Info-FarmLand");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, -1));

        tfBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBudgetKeyPressed(evt);
            }
        });
        jPanel1.add(tfBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, -1));

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if(tfBudget.getText().equals("") || tfName.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Fill all the empty spaces!","Error",1);
        else{
            name = tfName.getText();
            boolean flag;
            
            do{
                try{
                    BuildingSys.budget = Double.parseDouble(tfBudget.getText());
                    flag = false;
                }
                catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"Enter a numeric value for budget!","Error",1);                    
                    flag = true;
                    throw ex;
                }
            }while(flag);
            
            sff = new SetFarmFrame(name);
            sff.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void tfBudgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBudgetKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(tfBudget.getText().equals("") || tfName.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Fill all the empty spaces!","Error",1);
            else{
                name = tfName.getText();
                boolean flag;

                do{
                    try{
                        BuildingSys.budget = Double.parseDouble(tfBudget.getText());
                        flag = false;
                    }
                    catch(NumberFormatException ex){
                        JOptionPane.showMessageDialog(null,"Enter a numeric value for budget!","Error",1);                    
                        flag = true;
                        throw ex;
                    }
                }while(flag);

                sff = new SetFarmFrame(name);
                sff.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_tfBudgetKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfBudget;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
